version: '3.1'
services:
    graph_service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: graph_service
        restart: unless-stopped
        ports:
            - "8080:80"
            - "443:443"
        depends_on:
            - "graph_neo4j"
        links:
            - "graph_neo4j"
        networks:
            - backend

    graph_neo4j:
        platform: linux/x86_64
        image: neo4j:4.0.3
        hostname: graph_neo4j
        container_name: "graph_neo4j"
        environment:
            NEO4J_AUTH: neo4j/password
        ports:
            - "7474:7474"
            - "7687:7687"
        expose:
            - "7474"
            - "7687"
        volumes:
            - /tmp/neo4j/plugins:/plugins
            - /tmp/neo4j/data:/data
        networks:
            - backend


networks:
  backend:
    driver: bridge
    

    
    

  