version: '3.1'
services:
    graph_service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: graph_service
        restart: unless-stopped
        env_file: .env
        ports:
            - "8080:80"
            - "443:443"
        depends_on:
            - profile_neo4j
        links:
            - "profile_neo4j"
        networks:
            - backend

    profile_neo4j:
        
        image: neo4j:4.0.3
        hostname: neo4j
        container_name: neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        depends_on:
            - kafka
        volumes:
            - ./neo4j/plugins:/plugins
        # environment:
        #     NEO4J_AUTH: neo4j/streams
        #     NEO4J_dbms_logs_debug_level: DEBUG
        #     # KAFKA related configuration
        #     NEO4J_kafka_bootstrap_servers: kafka:19092
        #     NEO4J_streams_source_topic_nodes_neo4j: Person{*}
        #     NEO4J_streams_source_topic_relationships_neo4j: KNOWS{*}
        # expose:
        #     - "27017"
        networks:
            - backend


networks:
  backend:
    driver: nn

    
    

  